### ISSUE TITLE
Cascading world gen in the overworld

### ISSUE THREAD

**Issue by Insane96** [Insane-96/VulcaniteMod#13]

**Comment by Mindlessmrawesome** [comment]
I am having the same problem... 

`Vulcanite loaded a new chunk [22, -17] in dimension 0 (overworld) while populating chunk [23, -16], causing cascading worldgen lag.`

This mod and recurrent complex are for whatever reason causing cascading worldgen lag. I don't know how a mod that only spawns stuff in the nether could possibly cause this to happen in the _overworld_ but that's what the log says- dimension 0. 

Anyways until you get this figured out I'm gonna have to disable the mod, which is sad. (I liked vulcanite armor!)

**Comment by Insane96** [comment]
If you're using the latest version the cascading world gen is fake since
the overworld generation is disabled. Plus even when enabled is not a big
deal.

**Comment by Mindlessmrawesome** [comment]
so it was probably recurrent complex that was causing the majority of the lag...

**Comment by Insane96** [comment]
As said, if overworld ore gen is disabled the mod causes little to no lag
on generation (actually it should be none if it's disabled ... I really
don't know why you get the cascading world gen message)

Il Lun 11 Mar 2019, 22:29 Mindlessmrawesome <notifications@github.com> ha
scritto:
