### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by SissyTrashQueen** [Insane-96/VulcaniteMod#28]
MC version:  1.15.2
Forge version: 31.1.17
Mod version: [1.15.2] Vulcanite 2.0.2

Crash running my whole modlist.
Crash report: https://hastebin.com/esuweretax.pl
Error shown in the latest.log: https://hastebin.com/miqupomuru.rb

Running only this Vulcanite mod:
ERROR LOADING MODS
Vulcanite (vulcanite) has failed to load correctly
Type net.minecraftforge.common.loot.GlobalLootModifierSerializer not present
latest.log: https://hastebin.com/ehexaqeciq.md

**Comment by Insane96** [comment]
Update Forge
