### ISSUE TITLE
Server Crash [1.15.2]

### ISSUE THREAD

**Issue by Iastre** [Insane-96/VulcaniteMod#29]
Vulcanite crashes the server during launch.

Vulcanite: 2.0.2-mc1.15.2
Forge: 1.15.2-31.1.27
Server: GUI-less, Ubuntu Server

At a glance, it seems to be loading client code in a server-only setting.

Crash with whole modlist:
[crash-2020-03-23_15.09.41-server.txt](https://github.com/Insane96/VulcaniteMod/files/4371462/crash-2020-03-23_15.09.41-server.txt)

Crash with just Vulcanite:
[crash-2020-03-23_15.13.34-server.txt](https://github.com/Insane96/VulcaniteMod/files/4371463/crash-2020-03-23_15.13.34-server.txt)

**Comment by pabthelamb** [comment]
I'm experiencing this on 1.14.4 as well.

**Comment by Iastre** [comment]
I can confirm my problem fixed as of Vulcanite 2.0.3-1.15.2
