### ISSUE TITLE
Two Bugs

### ISSUE THREAD

**Issue by KXIIIS** [Insane-96/VulcaniteMod#35]
Hello. The first bug is a movement bug. As you can see in the video, whenever I try to move forward, there's some sort of glitch where I kind of stutter in place and it won't let me go forward. The second bug is that the vulcanite pickaxe doesn't drop the smelted ore, it just breaks the block. I'm on version 1.15.2.

https://imgur.com/a/dbnxeIy

**Comment by Insane96** [comment]
Does this happen with Vulcanite only?

Il Lun 13 Apr 2020, 19:00 KXIIIS <notifications@github.com> ha scritto:

**Comment by KXIIIS** [comment]
Are you referring to the movement bug?

**Comment by Insane96** [comment]
Also you should have made an Issue per bug.
I'm referring to both

**Comment by KXIIIS** [comment]
Ah, I’m sorry. I’m not really used to reporting bugs so I don’t know the proper etiquette yet. 

And yes, I’ve uninstalled the Vulcanite mod and the movement bug seemed to go away. And breaking an ore gives it’s drop with any pick axe. 

I tested the mod on its own and it worked fine, but then I added all my other mods back so maybe it’s interfering with another mod.

**Comment by KXIIIS** [comment]
Okay, I’ve figured out why I’m getting this bug. It’s because there’s something conflicting with Vulcanite and the mod Project MMO. Should I open an issue with them?

**Comment by Insane96** [comment]
Probably, I see no strange things done on my side.

**Comment by KXIIIS** [comment]
Okay, thank you for your time.

**Comment by KXIIIS** [comment]
Hey, so I got in touch with the head of Project MMO, and they said this: 
https://imgur.com/a/MXbleoJ

They also said you might be able to use this screenshot. 
![IMG_1945](https://user-images.githubusercontent.com/62857357/79347640-e7ddf780-7f01-11ea-809d-8378228e50c6.JPG)

**Comment by Insane96** [comment]
Could you copy-paste the talk? I can't check the gif as I can't stop it.

**Comment by KXIIIS** [comment]
Yes, my bad. 
![1](https://user-images.githubusercontent.com/62857357/79360250-a2c1c180-7f11-11ea-9b19-a438c4e19c47.PNG)
![2](https://user-images.githubusercontent.com/62857357/79360263-a6554880-7f11-11ea-864e-3bb6a828e726.PNG)
![3](https://user-images.githubusercontent.com/62857357/79360265-a6eddf00-7f11-11ea-8fc7-a07ed5320dc0.PNG)

**Comment by Insane96** [comment]
I can investigate this but I need you to use the latest version 2.6.8 of PMMO and send me the crash and also @Harmonized7 to push said version to github

**Comment by KXIIIS** [comment]
Sure thing. Harmonized7 said it's pushed. Thank you so much. 

[crash-2020-04-14_17.49.15-server.txt](https://github.com/Insane96/VulcaniteMod/files/4482723/crash-2020-04-14_17.49.15-server.txt)

**Comment by Insane96** [comment]
There we go, problem found. 
https://github.com/Harmonised7/project_mmo/blob/master/src/main/java/harmonised/pmmo/skills/XP.java#L750
Harmonized7 is passing no player to the LootContext.Builder
He should pass a `LootParameters.THIS_ENTITY` with the player.
