### ISSUE TITLE
Solidified Lava Causing Crash

### ISSUE THREAD

**Issue by TrueDakkon** [Insane-96/VulcaniteMod#38]
Version 1.15.2
When standing on lava in a lava pond(overworld), after a while the game will crash. Don't know if this is do to the player holding an item(I had a stick in my hand) or if this is because the action of trying to spawn the solidified lava is happening too quickly.
[Crash Report](https://pastebin.com/V6EcmyCa)

**Comment by Insane96** [comment]
You have so many mods, I can't repro this with only Vulcanite

**Comment by Insane96** [comment]
There's some kind of mod that let you walk on lava?

**Comment by TrueDakkon** [comment]
I have a couple of enchantment mods and I think one of them offers the lava walker enchantment.

**Comment by TrueDakkon** [comment]
I can try on another build and see if I still get the error.

**Comment by Insane96** [comment]
Should be fixed in 2.1 2

**Comment by TrueDakkon** [comment]
Found the mod causing this in case you want to look into it further.
[Crash Report](https://pastebin.com/RQseqhv2)
